### ISSUE TITLE
delta calculation error in recurrent network

### ISSUE THREAD

**Issue by SaraIqbal** [YuMan-Tam/deep-hedging-demo#6]
Dear YuMan,
There is an error in the delta calculation for the recurrent network. It works fine for the simple network.
When I ran this line:
 if share_stretegy_across_time is False:
    submodel = Delta_SubModel(model = model_recurrent, \
                      days_from_today = days_from_today)
  else:
    submodel = Delta_SubModel(model = model_recurrent, \
                      days_from_today = 0)
    
  nn_delta = submodel(I_range)

I got:
 Layer model_29 expects 2 input(s), but it received 1 input tensors.
Can you please seek out the problem? I tried changing the function Delta_SubModel but the problem still remains.
Thanks a lot for your help! I will really appreciate it!

**Comment by YuMan-Tam** [comment]
@SaraIqbal: Thanks for pointing out the error! The error arises because for the recurrent network, the stock price at t-1 becomes a state variable. So ```Delta_SubModel``` should take one more input, i.e. stock price at t-1. But the problem then is that the delta graph would have to be a 3D plot (a function of maturity and past stock price). The existing 2D delta plot would be insufficient. For this reason, I just stopped here as a proper fix would be a 2D plot for simple network and 3D plot for recurrent network...

One way to fix this is to add a conditional statement to detect a recurrent model, and then add an input to ```Delta_SubModel``` at a predetermined stock price (say at-the-money). This way you can keep the plot at 2D.
